### ISSUE TITLE
touch tmp/restart.txt always leads to connection refused

### ISSUE THREAD

**Issue by paulca** [puma/puma-dev#59]
I haven't been able to use `touch/tmp/restart.txt` with the latest release...

Here's what happens in the logs:

```
! App 'billing.tito' booted
! Killing 'billing.tito' (24599)
2016/08/10 12:13:08 http: proxy error: dial unix /Users/paulcampbell/.puma-dev/billing.tito/tmp/puma-dev-24598.sock: connect: connection refused
```

In the browser, the viewport just goes blank white.

unload/reload via launchctl works and is fast enough for me for now.

**Comment by evanphx** [comment]
@paulca What is happening in the browser when you're restarting? touching `tmp/restart.txt` seems to work fine in a trivial rack app.

**Comment by paulca** [comment]
@evanphx It just goes white (Chrome anyway). Super weird. I did just try it there and it did eventually restart after coming back to the computer after a while.

**Comment by evanphx** [comment]
@paulca That's odd. Would you be available to a screensharing session sometime so that I could see it in action?

**Comment by paulca** [comment]
Yep. It still seems to be happening with 0.9. Almost brand new Rails 5 apps.

**Comment by paulca** [comment]
(can do on screensharing)

**Comment by firedev** [comment]
I am using `touch tmp/restart.txt && rm tmp/restart.txt` it's a bit wonky but it works.

**Comment by tamalw** [comment]
I can replicate this issue.

App is working fine:

```
$ curl -I myapp.dev
HTTP/1.1 200 OK
…
```

I restart puma with `$ touch tmp/restart.txt`

`~/Library/Logs/puma-dev.log` says `! Killing 'myapp' (8593)`

Then I try to hit my app again:

```
$ curl -I myapp.dev
HTTP/1.1 500 Internal Server Error
Date: Thu, 22 Sep 2016 01:25:15 GMT
Content-Type: text/plain; charset=utf-8
```

And the logs only state `2016/09/21 20:25:15 http: proxy error: dial unix /Users/myuser/.puma-dev/myapp/tmp/puma-dev-863.sock: connect: connection refused`

I then run `$ rm tmp/restart.txt` according to @firedev and the logs state:

```
! Killing 'myapp' (8593)
* App 'myapp' shutdown and cleaned up
```

Then the app restarts as expected. The difference appears to be that the app never "shuts down and cleans up" when it's touched. Only when `tmp/restart.txt` is removed.

**Comment by jmay** [comment]
I just experienced this for the first time. I wonder if it's some sort of timestamp issue with the `restart.txt` file? I had not done a `touch tmp/restart.txt` in many days, maybe weeks. Deleting the file works, `touch` does not.

**Comment by pitops** [comment]
I can confirm that `touch tmp/restart.txt` is not working. `rm tmp/restart.txt` works though.

**Comment by johnksawers** [comment]
This is still happening, both the bug and the workaround.

**Comment by brunowego** [comment]
Thanks @firedev, your way works.

**Comment by attilagyorffy** [comment]
I am having the same issue. @evanphx we can screenshare if that helps. my go-fu is limited but am keen to learn to be able to help out.

**Comment by drosboro** [comment]
I am seeing exactly the same issue, and can confirm that the @firedev's workaround is working as expected.

**Comment by colorfulfool** [comment]
I was using puma-dev happily, until couple weeks ago, when I started getting this bug. I think it started right after upgrade from El Capitan to High Sierra — that might be a clue.

**Comment by CodyBrouwers** [comment]
I experienced the same issue on High Sierra with a Rails 5 app, and the above fix of `rm` the tmp restart file didn't help, what did help was running puma-dev in debug mode for a moment with `puma-dev -debug`. Not sure why that helped but it does seem like it could be a High Sierra issue.

**Comment by mitio** [comment]
What also worked for me was doing a `puma-dev -stop` to make it shut down all apps. The next attempt to access the app booted it properly.

**Comment by colorfulfool** [comment]
I just want to report that I'm no longer having this issue on High Sierra.

**Comment by alistairholt** [comment]
I'm still experiencing this issue with puma-dev version: 0.11 (go1.9.1). macOS 10.13.3.

**Comment by bjensen** [comment]
I get the same error and in the logs shows 10x: 

2018/08/07 09:30:05 http: proxy error: dial unix /Users/xx/.puma-dev/nordplaner/tmp/puma-dev-82192.sock: connect: connection refused

**Comment by attilagyorffy** [comment]
What I have personally seen so far is that hitting an app (via an HTTP request for example) straight after `touch tmp/restart.txt` results in a connection refused error.. If I wait a few more seconds, then everything is fine. I wonder whether that's related to the size of the app I'm trying to run. It may take a while for the Rails app to start listening, puma-dev then fails to route the requests to it until it's ready.

**Comment by evanphx** [comment]
Please reopen this if it's still an issue!

**Comment by bjensen** [comment]
This is still an issue: Way to reproduce: 

``` sudo puma-dev  --http-port 81 --https-port 443 -d dev:test:localhost```

Wait 30 minutes..and you get the connection refused: 

```  http: proxy error: dial unix /Users/xx/.puma-dev/nordplaner/tmp/puma-dev-82192.sock: connect: connection refused```

**Comment by johnmaxwell** [comment]
First of all, thank you for developing puma-dev! It seems like a good alternative to pow.

I'm seeing this too. Both `touch tmp/restart.txt` and `rm tmp/restart.txt` exhibit the described behavior in a hosted Rails 5.0.

Our application is a little odd, so I can understand why only some people are seeing the issue only sometimes. We have an "quote" endpoint that takes an AJAX request from client and fetches holds the connection open while it makes it's own HTTP request to a source server. It uses the informations from that HTTP request to respond to the AJAX request. 

In our development environment, we loop the request back to our own server, we have:

`| Browser| -- AJAX --> | myapp.test/quote | --HTTP--> | myapp.test/api/v1/get-quote |`

This is odd behavior, yes, but it is how we work in development to host the sort of API that we would be developing against. 

It is in this handle-two-requests-at-once scenario that I usually see encounter the problem. It usually occurs after I've ordered a restart. The first request begins processing, and then blocks on the second request, which fails to respond and times out after 60 seconds. 
This appears in the `puma-dev.log`

> 2019/01/03 14:30:13 http: proxy error: net/http: request canceled

After that fails, I can usually execute by bone-headed two-requests-at-the-same-time successfully. I imagine that there are other scenarios in which this would happen.

Based on what I'm seeing, it wouldn't surprise if the suggestion that the exiting process remains in the pool is correct. #175 

$ puma-dev -V
Version: v0.12 (go1.10.2)

**Comment by nonrational** [comment]
@yemartin @bjensen are you able to try to reproduce with the latest master @ https://github.com/puma/puma-dev/commit/338eaccfb43c199fb7e93fb2d62a5277fcf7a7dd ? i've been unable to reproduce on a number of ruby and puma versions on macOS 10.14.6.

see steps i used to attempt to reproduce here: https://github.com/puma/puma-dev/pull/175#issuecomment-523484693

**Comment by nonrational** [comment]
Please try to reproduce with the latest v0.13 and see if you're still seeing an issue. I believe updates to vendored dependencies addressed this.

**Comment by uson1x** [comment]
Unfortunately, just happened on puma-dev/0.14 for me (installed via brew on macOS 10.15.7)

**Comment by nonrational** [comment]
@uson1x Could you please try updating to `0.15.2`? If that doesn't fix the issue, please provide the output of `puma-dev -V; sw_vers; ruby -v; puma --version; rails --version`. Thanks.

**Comment by elsurudo** [comment]
I am still having this issue, and none of the above workaround are working. Output from above:

Version: 0.15.2 (go1.15.3)
ProductName:	macOS
ProductVersion:	11.2.3
BuildVersion:	20D91
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]
puma version 5.1.1
Rails 6.0.3

**Comment by nonrational** [comment]
A while ago, I had a patch up to ensure we remove apps from the pool correctly, but I wasn't able to reliably reproduce the issue. 

I will post a build with that patch for testing this week.

**Comment by elsurudo** [comment]
As a follow-up, the only way I can get puma working again after this happens is like so:

```
launchctl stop io.puma.dev
launchctl start io.puma.dev
```

**Comment by nonrational** [comment]
That's consistent with my understanding of the issue. `puma-dev` thinks the app is still running and will refuse to boot a new copy. Here's the previous patch I referred to: https://github.com/puma/puma-dev/pull/175/files.

**Comment by nonrational** [comment]
Resolved with https://github.com/puma/puma-dev/releases/tag/v0.16.0

**Comment by aelkoussy** [comment]
Still happening till now 
http: proxy error: dial unix /Users/username/.puma-dev/project_folder/tmp/puma-dev-RandomNumber.sock: connect: connection refused

puma-dev -V
Version: 0.18.2 (go1.17.6)
