### ISSUE TITLE
fish shell errors

### ISSUE THREAD

**Issue by marktran** [puma/puma-dev#69]
I have my login shell set to `/usr/local/bin/fish` and everytime an app boots, I see errors in `puma-dev.log`. The app seems to run fine despite the errors.

Any idea where these are coming from and is there anyway to get rid of them?

```
! Booting app '10x' on socket /Users/mark/.puma-dev/10x/tmp/puma-dev-84201.sock
10x[84351]: fish: Could not return shell to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: fish: Could not return shell to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: Could not send job 5 ('echo "begin; $argv "\n" ;end <&3 3<&-" | source 3<&0') to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: Could not send job 5 ('echo "begin; $argv "\n" ;end <&3 3<&-" | source 3<&0') to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: begin; function browse --wraps hub;  hub browse $argv; end
10x[84351]:  ;end <&3 3<&-
10x[84351]: fish: Could not return shell to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: fish: Could not return shell to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: fish: Could not return shell to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: fish: Could not return shell to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: fish: Could not return shell to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: Could not send job 5 ('echo "begin; $argv "\n" ;end <&3 3<&-" | source 3<&0') to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: Could not send job 5 ('echo "begin; $argv "\n" ;end <&3 3<&-" | source 3<&0') to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: begin; function c --wraps calc;  calc -d $argv; end
10x[84351]:  ;end <&3 3<&-
10x[84351]: fish: Could not return shell to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: fish: Could not return shell to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: fish: Could not return shell to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: fish: Could not return shell to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: fish: Could not return shell to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: Could not send job 5 ('echo "begin; $argv "\n" ;end <&3 3<&-" | source 3<&0') to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: Could not send job 5 ('echo "begin; $argv "\n" ;end <&3 3<&-" | source 3<&0') to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: begin; function e --wraps emacsclient;  emacsclient -nw -c $argv; end
10x[84351]:  ;end <&3 3<&-
10x[84351]: fish: Could not return shell to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: fish: Could not return shell to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: fish: Could not return shell to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: fish: Could not return shell to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: fish: Could not return shell to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: Could not send job 5 ('echo "begin; $argv "\n" ;end <&3 3<&-" | source 3<&0') to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: Could not send job 5 ('echo "begin; $argv "\n" ;end <&3 3<&-" | source 3<&0') to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: begin; function ip --wraps dig;  dig +short myip.opendns.com @resolver1.opendns.com $argv; end
10x[84351]:  ;end <&3 3<&-
10x[84351]: fish: Could not return shell to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: fish: Could not return shell to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: fish: Could not return shell to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: fish: Could not return shell to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: fish: Could not return shell to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: Could not send job 5 ('echo "begin; $argv "\n" ;end <&3 3<&-" | source 3<&0') to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: Could not send job 5 ('echo "begin; $argv "\n" ;end <&3 3<&-" | source 3<&0') to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: begin; function l --wraps ls;  ls  $argv; end
10x[84351]:  ;end <&3 3<&-
10x[84351]: fish: Could not return shell to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: fish: Could not return shell to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: fish: Could not return shell to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: fish: Could not return shell to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: fish: Could not return shell to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: Could not send job 5 ('echo "begin; $argv "\n" ;end <&3 3<&-" | source 3<&0') to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: Could not send job 5 ('echo "begin; $argv "\n" ;end <&3 3<&-" | source 3<&0') to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: begin; function l. --wraps ls;  ls -d .* $argv; end
10x[84351]:  ;end <&3 3<&-
10x[84351]: fish: Could not return shell to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: fish: Could not return shell to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: fish: Could not return shell to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: fish: Could not return shell to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: fish: Could not return shell to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: Could not send job 5 ('echo "begin; $argv "\n" ;end <&3 3<&-" | source 3<&0') to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: Could not send job 5 ('echo "begin; $argv "\n" ;end <&3 3<&-" | source 3<&0') to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: begin; function ll --wraps ls;  ls -l $argv; end
10x[84351]:  ;end <&3 3<&-
10x[84351]: fish: Could not return shell to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: fish: Could not return shell to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: fish: Could not return shell to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: fish: Could not return shell to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: fish: Could not return shell to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: Could not send job 5 ('echo "begin; $argv "\n" ;end <&3 3<&-" | source 3<&0') to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: Could not send job 5 ('echo "begin; $argv "\n" ;end <&3 3<&-" | source 3<&0') to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: begin; function t --wraps tree;  tree  $argv; end
10x[84351]:  ;end <&3 3<&-
10x[84351]: fish: Could not return shell to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: fish: Could not return shell to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: fish: Could not return shell to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: fish: Could not return shell to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: fish: Could not return shell to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: Could not send job 5 ('echo "begin; $argv "\n" ;end <&3 3<&-" | source 3<&0') to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: Could not send job 5 ('echo "begin; $argv "\n" ;end <&3 3<&-" | source 3<&0') to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: begin; function irssi --wraps ssh;  ssh mack -t 'screen -r irssi' $argv; end
10x[84351]:  ;end <&3 3<&-
10x[84351]: fish: Could not return shell to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: fish: Could not return shell to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: fish: Could not return shell to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: fish: Could not return shell to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: fish: Could not return shell to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: Could not send job 5 ('echo "begin; $argv "\n" ;end <&3 3<&-" | source 3<&0') to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: Could not send job 5 ('echo "begin; $argv "\n" ;end <&3 3<&-" | source 3<&0') to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: begin; function rtorrent --wraps ssh;  ssh east -t 'screen -r rtorrent' $argv; end
10x[84351]:  ;end <&3 3<&-
10x[84351]: fish: Could not return shell to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: fish: Could not return shell to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: fish: Could not return shell to foreground
10x[84351]: tcsetpgrp: Inappropriate ioctl for device
10x[84351]: Puma starting in single mode...
10x[84351]: * Version 2.9.1 (ruby 2.3.1-p112), codename: Team High Five
10x[84351]: * Min threads: 0, max threads: 5
10x[84351]: * Environment: development
```

**Comment by evanphx** [comment]
I have no idea. Maybe ask the fish developers?

**Comment by marktran** [comment]
cc @floam @ridiculousfish

**Comment by floam** [comment]
I think you need to finally upgrade fish. As far as I can tell the code that would produce that line is `#if 0`'d out and has been since 2012 to fix https://github.com/fish-shell/fish-shell/issues/121

What version are you using?

**Comment by marktran** [comment]
Thanks for taking a look, @floam.

I am actually running the latest version installed through Homebrew:
```
~ fish -v
fish, version 2.3.1
```
```
~ which fish
/usr/local/bin/fish
```
```
~ sw_vers -productVersion 
10.11.6
```
[fish config](https://github.com/marktran/tilde/tree/master/.config/fish)

**Comment by floam** [comment]
Whoops. I didn't look closely enough, the same string is output in two other spots.

**Comment by floam** [comment]
Can you make fish start with "-d2" here somehow?

**Comment by floam** [comment]
Is there anything funny that might be going on (I don't know what puma is) here with TTYs, or anything that might be making fish think it's in an interactive terminal session when it's not really? Does it happen if you move away `.config/fish`? What exactly is exec'ing fish?

**Comment by marktran** [comment]
It looks like the `alias` statements in my config are causing the errors. If I comment out any line that has `alias` in it then I don't see any errors.

[aliases.config file](https://github.com/marktran/tilde/blob/master/.config/fish/aliases.fish)

These might be relevant:

https://github.com/puma/puma-dev/issues/25

https://github.com/puma/puma-dev/blob/bf30b0e959a6fd2ccf19619dbbf762387866b0d4/dev/app.go#L267

**Comment by marktran** [comment]
With `-d2`:

```
! Booting app '10x' on socket /Users/mark/.puma-dev/10x/tmp/puma-dev-92153.sock
10x[92256]: fish: sourcing /usr/local/Cellar/fish/2.3.1/share/fish/config.fish
10x[92256]: fish: sourcing /usr/local/Cellar/fish/2.3.1/etc/fish/config.fish
10x[92256]: fish: sourcing /Users/mark/.config/fish/config.fish
10x[92256]: fish: Could not return shell to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: fish: Could not return shell to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: Could not send job 5 ('echo "begin; $argv "\n" ;end <&3 3<&-" | source 3<&0') to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: Could not send job 5 ('echo "begin; $argv "\n" ;end <&3 3<&-" | source 3<&0') to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: begin; function browse --wraps hub;  hub browse $argv; end
10x[92256]:  ;end <&3 3<&-
10x[92256]: fish: Could not return shell to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: fish: Could not return shell to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: fish: Could not return shell to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: fish: Could not return shell to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: fish: Could not return shell to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: Could not send job 5 ('echo "begin; $argv "\n" ;end <&3 3<&-" | source 3<&0') to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: Could not send job 5 ('echo "begin; $argv "\n" ;end <&3 3<&-" | source 3<&0') to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: begin; function c --wraps calc;  calc -d $argv; end
10x[92256]:  ;end <&3 3<&-
10x[92256]: fish: Could not return shell to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: fish: Could not return shell to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: fish: Could not return shell to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: fish: Could not return shell to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: fish: Could not return shell to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: Could not send job 5 ('echo "begin; $argv "\n" ;end <&3 3<&-" | source 3<&0') to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: Could not send job 5 ('echo "begin; $argv "\n" ;end <&3 3<&-" | source 3<&0') to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: begin; function e --wraps emacsclient;  emacsclient -nw -c $argv; end
10x[92256]:  ;end <&3 3<&-
10x[92256]: fish: Could not return shell to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: fish: Could not return shell to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: fish: Could not return shell to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: fish: Could not return shell to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: fish: Could not return shell to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: Could not send job 5 ('echo "begin; $argv "\n" ;end <&3 3<&-" | source 3<&0') to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: Could not send job 5 ('echo "begin; $argv "\n" ;end <&3 3<&-" | source 3<&0') to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: begin; function ip --wraps dig;  dig +short myip.opendns.com @resolver1.opendns.com $argv; end
10x[92256]:  ;end <&3 3<&-
10x[92256]: fish: Could not return shell to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: fish: Could not return shell to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: fish: Could not return shell to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: fish: Could not return shell to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: fish: Could not return shell to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: Could not send job 5 ('echo "begin; $argv "\n" ;end <&3 3<&-" | source 3<&0') to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: Could not send job 5 ('echo "begin; $argv "\n" ;end <&3 3<&-" | source 3<&0') to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: begin; function l --wraps ls;  ls  $argv; end
10x[92256]:  ;end <&3 3<&-
10x[92256]: fish: Could not return shell to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: fish: Could not return shell to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: fish: Could not return shell to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: fish: Could not return shell to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: fish: Could not return shell to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: Could not send job 5 ('echo "begin; $argv "\n" ;end <&3 3<&-" | source 3<&0') to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: Could not send job 5 ('echo "begin; $argv "\n" ;end <&3 3<&-" | source 3<&0') to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: begin; function l. --wraps ls;  ls -d .* $argv; end
10x[92256]:  ;end <&3 3<&-
10x[92256]: fish: Could not return shell to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: fish: Could not return shell to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: fish: Could not return shell to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: fish: Could not return shell to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: fish: Could not return shell to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: Could not send job 5 ('echo "begin; $argv "\n" ;end <&3 3<&-" | source 3<&0') to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: Could not send job 5 ('echo "begin; $argv "\n" ;end <&3 3<&-" | source 3<&0') to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: begin; function ll --wraps ls;  ls -l $argv; end
10x[92256]:  ;end <&3 3<&-
10x[92256]: fish: Could not return shell to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: fish: Could not return shell to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: fish: Could not return shell to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: fish: Could not return shell to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: fish: Could not return shell to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: Could not send job 5 ('echo "begin; $argv "\n" ;end <&3 3<&-" | source 3<&0') to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: Could not send job 5 ('echo "begin; $argv "\n" ;end <&3 3<&-" | source 3<&0') to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: begin; function t --wraps tree;  tree  $argv; end
10x[92256]:  ;end <&3 3<&-
10x[92256]: fish: Could not return shell to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: fish: Could not return shell to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: fish: Could not return shell to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: fish: Could not return shell to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: fish: Could not return shell to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: Could not send job 5 ('echo "begin; $argv "\n" ;end <&3 3<&-" | source 3<&0') to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: Could not send job 5 ('echo "begin; $argv "\n" ;end <&3 3<&-" | source 3<&0') to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: begin; function irssi --wraps ssh;  ssh mack -t 'screen -r irssi' $argv; end
10x[92256]:  ;end <&3 3<&-
10x[92256]: fish: Could not return shell to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: fish: Could not return shell to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: fish: Could not return shell to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: fish: Could not return shell to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: fish: Could not return shell to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: Could not send job 5 ('echo "begin; $argv "\n" ;end <&3 3<&-" | source 3<&0') to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: Could not send job 5 ('echo "begin; $argv "\n" ;end <&3 3<&-" | source 3<&0') to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: begin; function rtorrent --wraps ssh;  ssh east -t 'screen -r rtorrent' $argv; end
10x[92256]:  ;end <&3 3<&-
10x[92256]: fish: Could not return shell to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: fish: Could not return shell to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: fish: Could not return shell to foreground
10x[92256]: tcsetpgrp: Inappropriate ioctl for device
10x[92256]: Puma starting in single mode...
10x[92256]: * Version 2.9.1 (ruby 2.3.1-p112), codename: Team High Five
10x[92256]: * Min threads: 0, max threads: 5
10x[92256]: * Environment: development
```

**Comment by marktran** [comment]
This is fixed in the latest release of fish 2.4.0. See https://github.com/fish-shell/fish-shell/issues/3345.

**Comment by pirate** [comment]
@marktran I'm on fish 2.6.0 and this is still happening, exactly as described above when executing commands via SSH session.
